apiVersion: v1
data:
  loglevel.controller: warn
  loglevel.webhook: debug
  zap-logger-config: |
    {
      "level": "warn",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"loglevel.controller":"warn","loglevel.webhook":"debug","zap-logger-config":"{\n  \"level\": \"warn\",\n  \"development\": false,\n  \"outputPaths\": [\"stdout\"],\n  \"errorOutputPaths\": [\"stderr\"],\n  \"encoding\": \"json\",\n  \"encoderConfig\": {\n    \"timeKey\": \"ts\",\n    \"levelKey\": \"level\",\n    \"nameKey\": \"logger\",\n    \"callerKey\": \"caller\",\n    \"messageKey\": \"msg\",\n    \"stacktraceKey\": \"stacktrace\",\n    \"lineEnding\": \"\",\n    \"levelEncoder\": \"\",\n    \"timeEncoder\": \"iso8601\",\n    \"durationEncoder\": \"\",\n    \"callerEncoder\": \"\"\n  }\n}\n"},"kind":"ConfigMap","metadata":{"labels":{"app.kubernetes.io/name":"knative-eventing","app.kubernetes.io/version":"1.9.7","eventing.knative.dev/release":"v1.9.7","knative.dev/config-category":"eventing","knative.dev/config-propagation":"original"},"name":"config-logging","namespace":"knative-eventing","ownerReferences":[{"apiVersion":"operator.knative.dev/v1beta1","blockOwnerDeletion":true,"controller":true,"kind":"KnativeEventing","name":"knative-eventing","uid":"d60a27b8-fdc0-4438-9797-39d5c45fb156"}]}}
    manifestival: new
  creationTimestamp: "2024-10-25T05:44:14Z"
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.9.7
    eventing.knative.dev/release: v1.9.7
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  name: config-logging
  namespace: knative-eventing
  ownerReferences:
  - apiVersion: operator.knative.dev/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KnativeEventing
    name: knative-eventing
    uid: d60a27b8-fdc0-4438-9797-39d5c45fb156
  resourceVersion: "29870525"
  uid: 0e36015e-1f86-4f01-ab1f-3ae0da555b44
