apiVersion: v1
data:
  eventing-kafka: |
    kafka:
      brokers: kafka-cluster-kafka-bootstrap.5064-streaming.svc.cluster.local.:9092
      adminType: kafka
    cloudevents:
      maxIdleConns: 10000
      maxIdleConnsPerHost: 500
    dispatcher:
      cpuLimit: 500m
      cpuRequest: 300m
      memoryLimit: 4Gi
      memoryRequest: 50Mi
      podLabels:
        sidecar.istio.io/inject: "true"
      replicas: 5
    numPartitions: 3
    receiver:
      cpuLimit: 500m
      cpuRequest: 300m
      memoryLimit: 3Gi
      memoryRequest: 256Mi
      podLabels:
        sidecar.istio.io/inject: "true"
      replicas: 72
    replicationFactor: 3
    retentionDuration: 4320000000
  sarama: |
    Consumer:
      Fetch:
        Default: 1048576
        Max: 335544320
    Producer:
      MaxMessageBytes: 335544320
      Retry:
        Backoff: 1000
        Max: 5
    config: |
      Version: 2.6.0 # Kafka Version Compatibility From Sarama's Supported List (Major.Minor.Patch)
      Admin:
        Timeout: 10000000000  # 10 seconds
      Net:
        KeepAlive: 30000000000  # 30 seconds
        MaxOpenRequests: 1 # Set to 1 for use with Idempotent Producer
        TLS:
          Enable: false
        SASL:
          Enable: false
          Version: 1
      Metadata:
        RefreshFrequency: 300000000000  # 5 minutes
      Consumer:
        Offsets:
          AutoCommit:
            Interval: 5000000000  # 5 seconds
          Retention: 604800000000000  # 1 week
      Producer:
        Idempotent: true  # Must be false for Azure EventHubs
        RequiredAcks: -1  # -1 = WaitForAll, Most stringent option for "at-least-once" delivery.
    enableLogging: false
kind: ConfigMap
metadata:
  labels:
    argocd.argoproj.io/instance: sp-apac-prod2-knative-dist-chan-kafka
    kafka.eventing.knative.dev/release: v1.3.1
  name: config-kafka
  namespace: knative-eventing
