apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"eventing-kafka-channel-controller","argocd.argoproj.io/instance":"sp-apac-prod2-knative-dist-chan-kafka","kafka.eventing.knative.dev/release":"v1.3.1"},"name":"eventing-kafka-channel-controller","namespace":"knative-eventing"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"eventing-kafka-channel-controller","name":"eventing-kafka-channel-controller"}},"template":{"metadata":{"labels":{"app":"eventing-kafka-channel-controller","name":"eventing-kafka-channel-controller"}},"spec":{"containers":[{"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"SYSTEM_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"CONFIG_LOGGING_NAME","value":"config-logging"},{"name":"CONFIG_LEADERELECTION_NAME","value":"config-leader-election-kafkachannel"},{"name":"SERVICE_ACCOUNT","valueFrom":{"fieldRef":{"fieldPath":"spec.serviceAccountName"}}},{"name":"METRICS_PORT","value":"8081"},{"name":"METRICS_DOMAIN","value":"eventing-kafka"},{"name":"RECEIVER_IMAGE","value":"gcr.io/knative-releases/knative.dev/eventing-kafka/cmd/channel/distributed/receiver@sha256:f0c7dc32d840c897535211e69049699b3c84e9baccadb77636550b00d435deb9"},{"name":"DISPATCHER_IMAGE","value":"gcr.io/knative-releases/knative.dev/eventing-kafka/cmd/channel/distributed/dispatcher@sha256:08b2fa2a1a14a7bdaabc2744281f078efa920bea9882ff28e2d5db20f3cc6dac"}],"image":"gcr.io/knative-releases/knative.dev/eventing-kafka/cmd/channel/distributed/controller@sha256:5ee87a1f28a8ae973522623764c175671dc5545b5d7932829ba9e9521b6be01a","imagePullPolicy":"IfNotPresent","name":"eventing-kafka","ports":[{"containerPort":8081,"name":"metrics"}],"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true},"volumeMounts":[{"mountPath":"/etc/config-kafka","name":"config-kafka"}]}],"nodeSelector":{"deployment.group":"contentplatform-prod"},"serviceAccountName":"eventing-kafka-channel-controller","volumes":[{"configMap":{"name":"config-kafka"},"name":"config-kafka"}]}}}}
  creationTimestamp: "2024-11-01T05:48:19Z"
  generation: 1
  labels:
    app: eventing-kafka-channel-controller
    argocd.argoproj.io/instance: sp-apac-prod2-knative-dist-chan-kafka
    kafka.eventing.knative.dev/release: v1.3.1
  name: eventing-kafka-channel-controller
  namespace: knative-eventing
  resourceVersion: "160084592"
  uid: c6feace9-84df-4fc1-830b-02ab15209827
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eventing-kafka-channel-controller
      name: eventing-kafka-channel-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eventing-kafka-channel-controller
        name: eventing-kafka-channel-controller
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_LEADERELECTION_NAME
          value: config-leader-election-kafkachannel
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: METRICS_PORT
          value: "8081"
        - name: METRICS_DOMAIN
          value: eventing-kafka
        - name: RECEIVER_IMAGE
          value: gcr.io/knative-releases/knative.dev/eventing-kafka/cmd/channel/distributed/receiver@sha256:f0c7dc32d840c897535211e69049699b3c84e9baccadb77636550b00d435deb9
        - name: DISPATCHER_IMAGE
          value: gcr.io/knative-releases/knative.dev/eventing-kafka/cmd/channel/distributed/dispatcher@sha256:08b2fa2a1a14a7bdaabc2744281f078efa920bea9882ff28e2d5db20f3cc6dac
        image: gcr.io/knative-releases/knative.dev/eventing-kafka/cmd/channel/distributed/controller@sha256:5ee87a1f28a8ae973522623764c175671dc5545b5d7932829ba9e9521b6be01a
        imagePullPolicy: IfNotPresent
        name: eventing-kafka
        ports:
        - containerPort: 8081
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config-kafka
          name: config-kafka
      dnsPolicy: ClusterFirst
      nodeSelector:
        deployment.group: contentplatform-prod
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: eventing-kafka-channel-controller
      serviceAccountName: eventing-kafka-channel-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: config-kafka
        name: config-kafka
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-01T05:48:19Z"
    lastUpdateTime: "2024-11-01T05:48:25Z"
    message: ReplicaSet "eventing-kafka-channel-controller-78df654db" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-01T00:01:29Z"
    lastUpdateTime: "2024-12-01T00:01:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
