apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    duck.knative.dev/addressable: "true"
    kafka.eventing.knative.dev/release: v1.3.1
    knative.dev/crd-install: "true"
    messaging.knative.dev/subscribable: "true"
  name: kafkachannels.messaging.knative.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNlakNDQWlDZ0F3SUJBZ0lRYmVhT1hUQWJZUkhQTVlsdTNpellCREFLQmdncWhrak9QUVFEQWpCRE1SUXcKRWdZRFZRUUtFd3RyYm1GMGFYWmxMbVJsZGpFck1Da0dBMVVFQXhNaWEyRm1hMkV0ZDJWaWFHOXZheTVyYm1GMAphWFpsTFdWMlpXNTBhVzVuTG5OMll6QWVGdzB5TkRFeE1qWXdOREF3TkRaYUZ3MHlOREV5TURNd05EQXdORFphCk1FTXhGREFTQmdOVkJBb1RDMnR1WVhScGRtVXVaR1YyTVNzd0tRWURWUVFERXlKcllXWnJZUzEzWldKb2IyOXIKTG10dVlYUnBkbVV0WlhabGJuUnBibWN1YzNaak1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRQpWQUkvMHlPaEw2QndQdEtuL0pVWnkwQXlHTzlKVWYrSnFZTmQ2dVduS3VsNjJyVGoxRW9QVU42aEVFUGNUOTh2CjVOUDFpcyt6L28vVHF5dHNnNnFBSXFPQjlUQ0I4akFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbEJCWXcKRkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRQpGTWltNlZwUEJUT3dqNlU1TVRGV3c1UitQaVE3TUlHUUJnTlZIUkVFZ1lnd2dZV0NEV3RoWm10aExYZGxZbWh2CmIydUNIbXRoWm10aExYZGxZbWh2YjJzdWEyNWhkR2wyWlMxbGRtVnVkR2x1WjRJaWEyRm1hMkV0ZDJWaWFHOXYKYXk1cmJtRjBhWFpsTFdWMlpXNTBhVzVuTG5OMlk0SXdhMkZtYTJFdGQyVmlhRzl2YXk1cmJtRjBhWFpsTFdWMgpaVzUwYVc1bkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRDd0T2hUCll1cGNGMENZTFpuZ3MycHdZMDA1TU02N2l2aFRYWGZUNEhlV09nSWdYcWE1aFpiWVNieW1FZUNvV2dTWm5vOTEKN2Vtbis0RUFrNllSZUVUaVQ4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        service:
          name: kafka-webhook
          namespace: knative-eventing
          path: /resource-conversion
          port: 443
      conversionReviewVersions:
      - v1
      - v1beta1
  group: messaging.knative.dev
  names:
    categories:
    - all
    - knative
    - messaging
    - channel
    kind: KafkaChannel
    listKind: KafkaChannelList
    plural: kafkachannels
    shortNames:
    - kc
    singular: kafkachannel
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    - jsonPath: .status.address.url
      name: URL
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: KafkaChannel is a resource representing a Channel that is backed
          by a topic of an Apache Kafka cluster.
        properties:
          spec:
            description: Spec defines the desired state of the Channel.
            properties:
              delivery:
                description: DeliverySpec contains the default delivery spec for each
                  subscription to this Channelable. Each subscription delivery spec,
                  if any, overrides this global delivery spec.
                properties:
                  backoffDelay:
                    description: 'BackoffDelay is the delay before retrying. More
                      information on Duration format: - https://www.iso.org/iso-8601-date-and-time-format.html
                      - https://en.wikipedia.org/wiki/ISO_8601  For linear policy,
                      backoff delay is backoffDelay*<numberOfRetries>. For exponential
                      policy, backoff delay is backoffDelay*2^<numberOfRetries>.'
                    type: string
                  backoffPolicy:
                    description: BackoffPolicy is the retry backoff policy (linear,
                      exponential).
                    type: string
                  deadLetterSink:
                    description: DeadLetterSink is the sink receiving event that could
                      not be sent to a destination.
                    properties:
                      ref:
                        description: Ref points to an Addressable.
                        properties:
                          apiVersion:
                            description: API version of the referent.
                            type: string
                          kind:
                            description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                            type: string
                          namespace:
                            description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
                              This is optional field, it gets defaulted to the object
                              holding it if left out.'
                            type: string
                        type: object
                      uri:
                        description: URI can be an absolute URL(non-empty scheme and
                          non-empty host) pointing to the target or a relative URI.
                          Relative URIs will be resolved using the base URI retrieved
                          from Ref.
                        type: string
                    type: object
                  retry:
                    description: Retry is the minimum number of retries the sender
                      should attempt when sending an event before moving it to the
                      dead letter sink.
                    format: int32
                    type: integer
                type: object
                x-kubernetes-preserve-unknown-fields: true
              numPartitions:
                default: 1
                description: NumPartitions is the number of partitions of a Kafka
                  topic. By default, it is set to 1.
                format: int32
                type: integer
              replicationFactor:
                default: 1
                description: ReplicationFactor is the replication factor of a Kafka
                  topic. By default, it is set to 1.
                maximum: 32767
                type: integer
              retentionDuration:
                description: RetentionDuration is the retention time for events in
                  a Kafka Topic represented as an ISO-8601 Duration.  By default it
                  is set to 168 hours, which is the precise form of 7 days.
                type: string
              subscribers:
                description: This is the list of subscriptions for this subscribable.
                items:
                  properties:
                    delivery:
                      description: DeliverySpec contains options controlling the event
                        delivery
                      properties:
                        backoffDelay:
                          description: 'BackoffDelay is the delay before retrying.
                            More information on Duration format: - https://www.iso.org/iso-8601-date-and-time-format.html
                            - https://en.wikipedia.org/wiki/ISO_8601  For linear policy,
                            backoff delay is backoffDelay*<numberOfRetries>. For exponential
                            policy, backoff delay is backoffDelay*2^<numberOfRetries>.'
                          type: string
                        backoffPolicy:
                          description: BackoffPolicy is the retry backoff policy (linear,
                            exponential).
                          type: string
                        deadLetterSink:
                          description: DeadLetterSink is the sink receiving event
                            that could not be sent to a destination.
                          properties:
                            ref:
                              description: Ref points to an Addressable.
                              properties:
                                apiVersion:
                                  description: API version of the referent.
                                  type: string
                                kind:
                                  description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                                  type: string
                                name:
                                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                                  type: string
                                namespace:
                                  description: 'Namespace of the referent. More info:
                                    https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
                                    This is optional field, it gets defaulted to the
                                    object holding it if left out.'
                                  type: string
                              type: object
                            uri:
                              description: URI can be an absolute URL(non-empty scheme
                                and non-empty host) pointing to the target or a relative
                                URI. Relative URIs will be resolved using the base
                                URI retrieved from Ref.
                              type: string
                          type: object
                        retry:
                          description: Retry is the minimum number of retries the
                            sender should attempt when sending an event before moving
                            it to the dead letter sink.
                          format: int32
                          type: integer
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    generation:
                      description: Generation of the origin of the subscriber with
                        uid:UID.
                      format: int64
                      type: integer
                    replyUri:
                      description: ReplyURI is the endpoint for the reply
                      type: string
                    subscriberUri:
                      description: SubscriberURI is the endpoint for the subscriber
                      type: string
                    uid:
                      description: UID is used to understand the origin of the subscriber.
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: Status represents the current state of the KafkaChannel.
              This data may be out of date.
            properties:
              address:
                properties:
                  url:
                    type: string
                required:
                - url
                type: object
              annotations:
                description: Annotations is additional Status fields for the Resource
                  to save some additional State as well as convey more information
                  to the user. This is roughly akin to Annotations on any k8s resource,
                  just the reconciler conveying richer information outwards.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              conditions:
                description: Conditions the latest available observations of a resource's
                  current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition
                        transitioned from one status to another. We use VolatileTime
                        in place of metav1.Time to exclude this from creating equality.Semantic
                        differences (all other things held constant).
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    severity:
                      description: Severity with which to treat failures of this type
                        of condition. When this is not specified, it defaults to Error.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition.
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
              deadLetterChannel:
                description: DeadLetterChannel is a KReference and is set by the channel
                  when it supports native error handling via a channel Failed messages
                  are delivered here.
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
                      This is optional field, it gets defaulted to the object holding
                      it if left out.'
                    type: string
                type: object
              deadLetterSinkUri:
                description: DeadLetterSinkURI is the resolved URI of the dead letter
                  ref if one is specified in the Spec.Delivery.
                type: string
              observedGeneration:
                description: ObservedGeneration is the 'Generation' of the Service
                  that was last processed by the controller.
                format: int64
                type: integer
              subscribers:
                description: This is the list of subscription's statuses for this
                  channel.
                items:
                  properties:
                    message:
                      description: A human readable message indicating details of
                        Ready status.
                      type: string
                    observedGeneration:
                      description: Generation of the origin of the subscriber with
                        uid:UID.
                      format: int64
                      type: integer
                    ready:
                      description: Status of the subscriber.
                      type: string
                    uid:
                      description: UID is used to understand the origin of the subscriber.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - all
    - knative
    - messaging
    - channel
    kind: KafkaChannel
    listKind: KafkaChannelList
    plural: kafkachannels
    shortNames:
    - kc
    singular: kafkachannel
  conditions:
  - lastTransitionTime: "2024-10-16T06:26:46Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-10-16T06:26:46Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
