apiVersion: v1
data:
  loglevel.controller: "warn"
  loglevel.webhook: "debug"
  zap-logger-config: |
    {
      "level": "warn",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
kind: ConfigMap
metadata:
  annotations:
    manifestival: new
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.9.7
    eventing.knative.dev/release: v1.9.7
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  name: config-logging
  namespace: knative-eventing
  ownerReferences:
  - apiVersion: operator.knative.dev/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KnativeEventing
    name: knative-eventing
    uid: d60a27b8-fdc0-4438-9797-39d5c45fb156
